version: '3.8'

x-faraway-build: &default-faraway-build
  image: debian:bullseye-slim
  env_file: ${ENV_FILE}
  profiles:
    - default
  volumes:
    - ./dist/server:/usr/local/bin/server
    - ./dist/client:/usr/local/bin/client
  networks:
    - faraway

services:

  server:
    expose:
      - "${SERVER_PORT}"
    <<: *default-faraway-build
    command: "server"

  client:
    <<: *default-faraway-build
    depends_on:
      - server
    command: "client"

  migrations:
    build:
      context: .
      dockerfile: dockerfiles/migrations.Dockerfile
    env_file:
      - ${ENV_FILE}
    networks:
      - faraway
    profiles:
      - migration

  postgresdb:
    image: postgres:14.8
    expose:
      - "5432"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=faraway-db
    volumes:
      - db-data:/var/lib/postgresql/data
    command: "-c log_statement=all"
    networks:
      - faraway
    profiles:
      - database

  redis:
    image: "redis:7-alpine"
    expose:
      - "6379"
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    command: redis-server
    networks:
      - faraway
    profiles:
      - cache

  integration-test:
    build:
      context: .
      dockerfile: dockerfiles/integration-test.Dockerfile
    env_file:
      - .env
    networks:
      - faraway
    profiles:
      - integration-test

  test-executor:
    image: alpine:3
    volumes:
      - ./tools/dist/run_e2e:/usr/local/bin/run_e2e
      - ./tools/dist/venom:/usr/local/bin/venom
      - ./test-outputs:/outputs
      - ./test:/test
    env_file: ${ENV_FILE}
    entrypoint: /usr/local/bin/run_e2e
    command: ${SUITE:-*/*/*.yml}
    networks:
      - faraway
    profiles:
      - testing

volumes:
  redis:
  db-data:

networks:
  faraway:
    driver: bridge
